# global section - you can override image in job section
# stages - shows the order of execution
image: node
stages:
  - caching
  - build
  - test
  - deploy to staging
  - deploy to production
  - production tests

variables:
  STAGING_DOMAIN: zoota-staging.surge.sh
  PRODUCTION_DOMAIN: zoota.surge.sh

# cache like node_modules we can generate every time when pipeline runs
# Policy - default is push and pull. We can't set policy at global level
# We do not need to pull cache for this job
# except - you can define when to run/not run job section
# only - you can specify this option to run this job only schedules
# to disable the job - add `.` in front of the title of the job
#                     example - .create cache:
create cache:
  stage: caching
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  except:
    - schedules  
update cache:
  stage: caching
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push  
  only:
    - schedules
build-website:
  stage: build
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public
  except:
    - schedules  
test artifact:
  cache: {}
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html
  except:
    - schedules  

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
  except:
    - schedules  

# environment - to specify where you want to deploy    
deploy to staging:
  cache: {}
  stage: deploy to staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  script:
    - npm install -g surge
    - surge --project ./public --domain $STAGING_DOMAIN
  except:
    - schedules  

# when: manual - this will add a manual step and stop deploying to prod automatically
# allow_failure: false - this will block subsequent jobs to run until manual verification is passed
deploy to production:
  cache: {}
  stage: deploy to production
  environment:
    name: production
    url: http://$PRODUCTION_DOMAIN
  when: manual
  allow_failure: false
  script:
    - npm install -g surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN
  except:
    - schedules  

post production tests:
  cache: {}
  stage: production tests
  script:
    - curl -s "http://zoota.surge.sh/" | tac | tac | grep -q "Gatsby"
    - curl -s "http://zoota.surge.sh/" | tac | tac | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules  
